name 'my_world'
depends 'chef-client'
depends 'apt'
depends 'ntp'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures my_world'
long_description 'Installs/Configures my_world'
version '0.1.0'

